### ISSUE TITLE
Clicking with middle mouse on links does not open them in new tabs

### ISSUE THREAD

**Issue by zvirdaniel** [alcinnz/Odysseus#59] opened 2018-01-01 13:30 UTC
When I click a link with my middle mouse in other browsers, it opens those links in the background in new tabs. I use this practically permanently, and having this would make this browser just a bit more usable.

**Comment by alcinnz** [comment] 2018-01-01 19:26
Easy fix, once I found https://valadoc.org/webkit2gtk-4.0/WebKit.NavigationAction.get_modifiers.html. Fix coming soon.

**Comment by alcinnz** [comment] 2018-01-01 20:00
Well the link before would implement ctrl+click, https://valadoc.org/webkit2gtk-4.0/WebKit.NavigationAction.get_mouse_button.html is a better fit for your issue.

I'll use both.

**Comment by alcinnz** [comment] 2018-01-01 21:34
Fix committed and tested. It will be live in the AppCenter in a day or so.

**Comment by alcinnz** [comment] 2018-01-01 22:55
Sorry, found a mouse to test middle-click with and discovered this isn't quite fixed.

**Comment by alcinnz** [comment] 2018-01-01 23:02
Now it's fully working.Turns out I count my mouse buttons differently to how GNOME does it.

**Comment by alcinnz** [comment] 2018-01-01 23:04
Interestingly, I was able to make the code for this *very* self-contained: https://github.com/alcinnz/Odysseus/blob/master/src/Traits/navigate/newtab.vala

**Comment by alcinnz** [comment] 2018-01-02 00:14
Just caught a regression on this with the addition of autoscroll. It is fixed yet again now.

**Comment by zvirdaniel** [comment] 2018-01-02 15:23
It works, but not quite as expected. You see, in all other browsers, it opens the link a new tab, in the background (and loads it). Imagine using a service like feedly, or basically any RSS reader. I click on 10 links with my middle button, because I want to read them later, so they all open in new tabs, and load themselves. I read them afterwards.

**Comment by alcinnz** [comment] 2018-01-02 19:10
I'll set all new tabs to open in the background. It wasn't something I was settled on anyways.

**Comment by alcinnz** [comment] 2018-01-02 21:47
Fix committed, hopefully it'll be live today. 

Also Odysseus should look a bit sleeker now that I've reduce how often the "Loading..." label shows.

**Closed by alcinnz** 2018-01-02 21:47 UTC
