### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by giovannicaligaris** [alcinnz/Odysseus#67] opened 2018-01-03 22:31 UTC
If I zoom some of the pages, eventually Odysseus will crash and can't launch anymore. Keep getting 'Segmentation faul' error.

The only way to solve it is to deleted the config files

rm -R '~/.config/com.github.alcinnz.odysseus' 

```
$ com.github.alcinnz.odysseus 
[INFO 22:28:36.398712] Application.vala:154: Odysseus version: 0.3
[INFO 22:28:36.398747] Application.vala:156: Kernel version: 4.10.0-42-generic
1
[FATAL 22:28:36.489039] [Gtk] gtk_entry_set_text: assertion 'text != NULL' failed
[FATAL 22:28:36.521914] [Gtk] gtk_notebook_get_tab_label: assertion 'GTK_IS_WIDGET (child)' failed
[FATAL 22:28:36.522628] [Gtk] gtk_entry_set_text: assertion 'text != NULL' failed
[FATAL 22:28:36.560596] [Gtk] gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed
[FATAL 22:28:36.588533] [Gtk] gtk_notebook_get_tab_label: assertion 'GTK_IS_WIDGET (child)' failed
[FATAL 22:28:36.589207] [Gtk] gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed
[FATAL 22:28:36.590046] [Gtk] gtk_entry_set_text: assertion 'text != NULL' failed
[FATAL 22:28:36.645426] odysseus_templating_std_i18n_lookup_translation: assertion '*formula != NULL' failed
[FATAL 22:28:36.645601] [GLib] g_strsplit: assertion 'string != NULL' failed
Segmentation fault
```

**Comment by alcinnz** [comment] 2018-01-04 00:39
I'm not clear how to reproduce this error. Can you please so how quickly you can trigger this crash from a blank config and send me, and once you do send me the ui.sqlite file from that directory?

I'd recommend you back up your configuration with `mv ~/.config/com.github.alcinnz.odysseus ~/.config/com.github.alcinnz-backup`, and that'll clear your configuration so it's as simple as possible for me to understand what's happening when you send it to me.

**Comment by alcinnz** [comment] 2018-01-04 00:57
Also please give me a count of how many times you zoomed in and one which page. That may help me in my testing.

**Comment by alcinnz** [comment] 2018-02-12 21:37
I'm investigating this issue, and am not seeing the crash.

I'm thinking I might limit the range of how far the page can be zoomed, but I'm not sure that'll fix this issue.

**Comment by giovannicaligaris** [comment] 2018-02-13 18:08
I am not able to replicate it again. I don't know why. But I have noticed that if I zoom on a page then close that tab and try to re-open the same webpage later, it will not remember that I zoomed on that site before.

Usually I can do this with Chrome and all the other commercial websites.

**Comment by alcinnz** [comment] 2018-02-13 21:50
I'll have to mark this as help-wanted. While it's not a trivial task, I don't think it'll be too hard. 

That said I have other priorities.

**Comment by alcinnz** [comment] 2018-03-06 08:11
Just opened a [new issue](https://github.com/alcinnz/Odysseus/issues/73) for persisting the zoom levels, and since we've reproduced the titular crash I'll close this issue.

Tomorrow I'll aim to close some of the other issues.

**Closed by alcinnz** 2018-03-06 08:11 UTC
