### ISSUE TITLE
Youtube freezes

### ISSUE THREAD

**Issue by giovannicaligaris** [alcinnz/Odysseus#88] opened 2018-03-20 18:08 UTC
Playing the video works fine. The image will freeze when trying to skip/fast forward the video but the audio will keep playing normally.

Is this a flash/html5 issue?

**Comment by giovannicaligaris** [comment] 2018-03-20 18:12
This is what I'm getting on https://www.youtube.com/html5

![screenshot from 2018-03-20 18 12 09](https://user-images.githubusercontent.com/26255347/37674229-42de6c88-2c6a-11e8-9298-97717622e808.png)

**Comment by alcinnz** [comment] 2018-03-20 19:19
I don't know all the details here, but I can say:

• it's not a Flash issue, since I decided that as a new browser in the 2010s I won't support plugins at all. 
• As suggested by your picture (& beyond it) Odysseus is extremely lenient in it's video format support. It supports practically every movie format under the sun. 
• There's a blogpost somewhere describing how tricky it is to implement SME because of this (EME too, but there's an additional political aspect there as well and I come out against it). 

---

I'll check that the issue doesn't occur for the simplest of video playback, say on [ar.al](https://ar.al).

**Comment by giovannicaligaris** [comment] 2018-03-20 19:36
I tried the link you posted and I am also having the same issue.

I do have ubuntu-restricted-extras installed, which has all the video and audio codecs.

**Comment by alcinnz** [comment] 2018-03-20 20:05
O.K., I see that now. And I now know the scope of the issue.

I'll see if this has been reported to WebKitGTK, but I think I can fix it short-term by running some JavaScript in the tabs onclose.

**Comment by alcinnz** [comment] 2018-03-20 20:10
I'm not seeing the issue reported there, but it'll be easy enough to fix it myself in Odysseus.

**Comment by alcinnz** [comment] 2018-03-20 20:33
Just committed and tested a fix, which I'll send through the release pipeline today.

So expect to see in update in the next few days with this and a few other fixes, as well as a nicer history viewer.

**Comment by alcinnz** [comment] 2018-03-20 20:44
The fix, by the way was just [3 lines of code](https://github.com/alcinnz/Odysseus/blob/master/src/Traits/decorate/fix-bg-videos.vala).

**Comment by alcinnz** [comment] 2018-03-20 21:32
Spotted some regressions as I played with it more seriously, so I'm now playing around with what works best.

**Comment by giovannicaligaris** [comment] 2018-03-20 21:34
Thank you

**Comment by alcinnz** [comment] 2018-03-20 21:53
Now the fix is more integrated into the UI code then I'd like, but it works correctly. Committing now.

**Comment by giovannicaligaris** [comment] 2018-03-22 08:48
I just updated to 1.2.2 and I am still having the same issue on youtube and https://ar.al. The video starts fine but when skipping the image freezes and the audio continues to play normally.

Also, when I execute Odysseus from terminal this is what it looks like.

`$ com.github.alcinnz.odysseus 
[INFO 08:46:56.900927] Application.vala:154: Odysseus version: 1
[INFO 08:46:56.901120] Application.vala:156: Kernel version: 4.15.11-041511-generic
3
[FATAL 08:46:57.091062] [Gtk] gtk_entry_set_text: assertion 'text != NULL' failed
[FATAL 08:46:57.181055] [Gtk] gtk_notebook_get_tab_label: assertion 'GTK_IS_WIDGET (child)' failed
[FATAL 08:46:57.181231] [Gtk] gtk_entry_set_text: assertion 'text != NULL' failed
[FATAL 08:46:57.218421] [Gtk] gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed
[FATAL 08:46:57.248783] [GLib] g_strsplit: assertion 'string != NULL' failed
`

**Comment by alcinnz** [comment] 2018-03-22 19:54
O.K., that's a slightly different issue to the one I fixed. And I believe one that'll probably need to be fixed be fixed in WebKitGTK. The actual video playback software should be fine though as it's shared with Audience and I don't see the issue there.

What I fixed was to stop the video from continuing to play after a tab is closed. So still, a big improvement.

**Comment by alcinnz** [comment] 2018-05-26 02:07
This appears to have been fixed upstream, as I'm no longer experiencing any of these issues. I'll leave my fix in there still as it's quite harmless.

Please reopen this issue if you're facing something different.

**Closed by alcinnz** 2018-05-26 02:07 UTC
Labels: bug, third party
