### ISSUE TITLE
Add availibilty to choose search engine

### ISSUE THREAD

**Issue by NathanBnm** [alcinnz/Odysseus#170] opened 2019-05-12 10:05 UTC
This would be great to have the possibility to choose our search engine.

**Comment by alcinnz** [comment] 2019-05-12 21:18
It's my roadmap! As I'm not fond of centralization on any given website.

I'm thinking of combining results from multiple search engines, or if they don't readily support that using your most recently used search engine. And making it a single click to add any search engine you have open.

Beyond that it's trivial to write code that sends your search to any search engine, but the autocompletions takes a bit more work. I don't know how to deal with the latter.

**Comment by alcinnz** [comment] 2019-05-13 00:14
Duplicate of #79, or possibly #115.

I'm happy to discuss these ideas there.

**Closed by alcinnz** 2019-05-13 00:14 UTC
