### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by giovannicaligaris** [alcinnz/Odysseus#124] opened 2018-08-23 13:29 UTC
It would be nice if it was hosted on Flathub.

**Comment by alcinnz** [comment] 2018-08-23 21:27
Thanks for letting me know this is desired! I'll look into how to do this again.

**Comment by alcinnz** [comment] 2018-08-24 07:11
I've just looked into this a little and found a couple of manifest files that serves as a useful reference for writing mine:

https://github.com/flathub/org.gnome.FeedReader/blob/master/org.gnome.FeedReader.json
https://github.com/flathub/com.github.bleakgrey.tootle/blob/master/com.github.bleakgrey.tootle.json
https://github.com/BharatKalluri/tootle-flatpak/blob/master/com.github.bleakgrey.tootle.json

I also checked for the pivotal WebKitGTK dependency in the runtimes. I found it in the GNOME runtime (not the FreeDesktop.Org runtime), and am pleased to see that runtime was updated just last week. This helps assure me that by doing this I won't be exposing you to the dangers of out-of-date browser engines.

**Comment by alcinnz** [comment] 2018-08-25 08:56
It turns out GNOME Web isn't comfortable releasing to FlatHub given the out-of-date GnuTLS.

I'll still release a flatpak as my investigations indicate I won't be exposing people to viruses too badly, but I won't publish it to FlatHub as I wouldn't trust the security of HTTPS connections in that build.

**Comment by alcinnz** [comment] 2018-09-01 04:29
I've written most of an flatpak manifest for Odysseus. The issue is that I've failed to incorporate my libappstream via it's libstemmer dependency. I can't seem to configure the right build system for it.

I don't actually need this feature of libappstream though so maybe there's some way to tell libappstream's build system that...

**Comment by alcinnz** [comment] 2018-09-01 09:27
I've got a FlatPak manifest for Odysseus. Please open new issues for any problems you have running it.

**Comment by giovannicaligaris** [comment] 2018-09-01 13:29
Can you host it on Flathub?

**Comment by alcinnz** [comment] 2018-09-01 18:00
No, I am not comfortable doing so if GNOME Web is complaining about outdated gnuTLS.

But I am happy to host a FlatPak repository for it on the project website. Because at least WebKitGTK's up-to-date.

**Comment by alcinnz** [comment] 2018-09-01 20:28
I think I've just committed a fix that should stop the flatpak from crashing on start, but I have not yet tested it.

I only know it builds.

**Comment by alcinnz** [comment] 2018-09-02 06:30
I heard it confirmed that it runs, and can access the Internet!

**Closed by alcinnz** 2018-09-02 06:30 UTC

**Comment by giovannicaligaris** [comment] 2018-09-02 06:39
How can I test it?

**Comment by alcinnz** [comment] 2018-09-02 08:10
The commands:

    mkdir flatpak-build
    flatpak-builder --run flatpak-build data/com.github.alcinnz.odysseus.json

Should do it. And I think I'll open a seperate issue for distributing a pre-built result from similar commands.
